---
object_type: method
version: 1.0
object:
  attributes:
    name: ovirt_best_fit_cluster
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
  inputs: []
