---
object_type: method
version: 1.0
object:
  attributes:
    name: vmware_best_fit_with_scope
    display_name:
    description:
    scope: instance
    language: ruby
    location: inline
  inputs: []
