---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: InfrastructureConfiguredSystemMiqProvisionComplete
    inherits:
    description:
  fields:
  - to:
      value: "${/#miq_provision.miq_request.get_option(:owner_email)} || ${/#miq_provision.miq_request.requester.email}
        || ${/Configuration/Email/Default#default_recipient}"
  - mail_method:
      value: "#stop_email"
