---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: ServiceReconfigureRequestApproverApproved
    inherits:
    description:
    relative_path: System/Notification/Email/ServiceReconfigureRequestApproverApproved
  fields:
  - subject:
      value: Request ID ${/#miq_request.id} - Service Request received from ${/#miq_request.requester.email}
        was Approved.
  - body:
      value: 'Approver,<br/><br/>Service Request received from ${/#miq_request.requester.email}
        was Approved.<br/><br/>Approvers reason : ${/#miq_request.reason}<br/><br/>To
        view this Request go to : <a href=${/#miq_request.show_url}>${/#miq_request.show_url}</a><br/><br/>
        Thank you,<br/> ${#signature}'
