---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: ServiceReconfigureRequestRequesterApproved
    inherits:
    description:
    relative_path: System/Notification/Email/ServiceReconfigureRequestRequesterApproved
  fields:
  - to:
      value: "${/#miq_request.get_option(:owner_email)} || ${/#miq_request.requester.email}
        || ${/Configuration/Email/Default#default_recipient}"
  - subject:
      value: Request ID ${/#miq_request.id} - Your Service Request was Approved, pending
        Quota Validation.
  - body:
      value: 'Hello,<br/><br/>Your Service Request was Approved. If Service reconfiguration
        is successful you will be notified via email when the Service is reconfigured.<br/><br/>Approvers
        notes : ${/#miq_request.reason}<br/><br/>To view this Request go to : <a href=${/#miq_request.show_url}>${/#miq_request.show_url}</a><br/><br/>
        Thank you,<br/> ${#signature}'
