---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: ServiceReconfigureRequestApproverPending
    inherits:
    description:
    relative_path: System/Notification/Email/ServiceReconfigureRequestApproverPending
  fields:
  - subject:
      value: Request ID ${/#miq_request.id} - Service Request from ${/#miq_request.requester.email}
        Pending Approval.
  - body:
      value: 'Approver,<br/><br/>A Service Request received from ${/#miq_request.requester.email}
        is Pending.<br/><br/>For more information you can go to : <a href=${/#miq_request.show_url}>${/#miq_request.show_url}</a><br/><br/>
        Thank you,<br/> ${#signature}'
