---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: Default
    inherits:
    description:
    relative_path: Service/Reconfigure/StateMachines/ServiceReconfigureRequestApproval/Default
  fields: []
