---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: ServiceReconfigureRequest_denied
    inherits:
    description:
    relative_path: System/Policy/ServiceReconfigureRequest_denied
  fields:
  - rel5:
      value: "/System/Notification/Email/ServiceReconfigureRequestRequesterDenied"
  - rel6:
      value: "/System/Notification/Email/ServiceReconfigureRequestApproverDenied"
