---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: ServiceReconfigureRequest_created
    inherits:
    description:
    relative_path: System/Policy/ServiceReconfigureRequest_created
  fields:
  - rel6:
      value: "/Service/Reconfigure/StateMachines/ServiceReconfigureRequestApproval/Default"
