---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: ServiceReconfigureRequest_approved
    inherits:
    description:
    relative_path: System/Policy/ServiceReconfigureRequest_approved
  fields:
  - rel5:
      value: "/System/Notification/Email/ServiceReconfigureRequestRequesterApproved"
  - rel6:
      value: "/System/Notification/Email/ServiceReconfigureRequestApproverApproved"
