---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: ServiceReconfigureRequest_pending
    inherits:
    description:
    relative_path: System/Policy/ServiceReconfigureRequest_pending
  fields:
  - rel5:
      value: "/System/Notification/Email/ServiceReconfigureRequestRequesterPending"
  - rel6:
      value: "/System/Notification/Email/ServiceReconfigureRequestApproverPending"
